### PR TITLE
SQL_SELECT_HW

### PR DESCRIPTION
**Pull request by Volod980**
I split all tasks into different files, I think it will be more comfortable. If it is not good idea I will put them to one file. Have a nice day!

### CODE REVIEW

**Review by albusel — CHANGES_REQUESTED** [review]
Hi Volodymyr,

Thanks for the work you've done.
My comments are below. It's supposed that you'll fix all the points.

Part 1 task 1
While applying filtering based on string it would be useful to use UPPER/LOWER function to bring values to one case.

LEFT JOIN is used in the query, however in WHERE clause filtering based on the table "category" is applied, so the correct join type is INNER.

Part 1 task 2 
The same mistake with join type as in the previous task.
There is no need to select required columns in subqueries after join, you can address these columns directly in SELECT.
While working with dates, it's crucial to use function to bring dates to one format. For example, TO_DATE function.

Part 1 Task 3
group by first_name, last_name is used, while there may be several actors with the same name. To provide uniqueness, unique identified (ID) should be used.

Repeating error with JOIN types. Please, revise carefully the theory about them.

Plain LIMIT isn't the best option, since we may have several actors with the same number of films, but only the first one would be included in the result set.

Part 1 Task 4
JOIN types :(

UPPER/LOWER function is required.

Subquery after JOIN isn't required.



Part 1 Task 5
UPPER/LOWER function should be used.

LEFT JOIN :(

Movies titles are doubled in the result set.

Part 2 Task 1
As it's given in the task, "You cannot use window functions".

Wrong join type is used.

LIMIT doesn't allow to see whether there are employees with the same amount. 

Part 2 Task 2
LEFT JOIN :(

Proposed in the task description film rating system wasn't used. As your customer I'm not satisfied.

No ';' at the end of the query.

Plain LIMIT.

Part 3
No ';' at the end of the query.
Incorrect used of left join.
Just a list is provided with number for each actor, while an answer the question had been expected.

Meaningful comments would be enough in the scripts, no need for a particular doc.

**Comment by Volod980** [comment]
Hello, thank you very much for your  comments. I really appreciate it. 
I have several questions:
1. Part 2, task 2. This information of rating system I found in the internet and my question is like : 'what the information of film rating system should I use ?'
2.  Part 3. I can not understand this comment: "Just a list is provided with number for each actor, while an answer the question had been expected". can you explain please ?

**Comment by Volod980** [comment]
Hello, I changed old files to the new ones with updated information. Could you please check them ?

**Review by albusel — COMMENTED** [review]
In every task the issue with JOIN type hasn't been fixed. LEFT JOIN is incorrect JOIN type.

Task 2.1: ORDER BY doesn't guarantee the required order of records while manipulating them, it's useful in SELECT statements and not to be used in subquery. We should think about other option to find the last store. 

No ';' at the end of the query.

**Comment by Volod980** [comment]
Hello, thank you for your comments. I have updated all the files. For task 2, part 1 "Order by" in the specified last store is not mandatory.

**Review by albusel — APPROVED** [review]
Approved, you can merge

**Pull request merged**
