### PR TITLE
DB_HW_Subway

### PR DESCRIPTION
**Pull request by Volod980**

### CODE REVIEW

**Comment by albusel** [comment]
Hi Volodymyr,
Not the best colors are chosen, relationships are complicated to follow.

The 1st page of the template of the business description wasn't updated in accorded with your topic.

I would recommend to add other constraints, like for example check if employee's date of birth is a valid date.

**Review by albusel — CHANGES_REQUESTED** [review]
Hi Volodymyr,
Not the best colors are chosen, relationships are complicated to follow.

The 1st page of the template of the business description wasn't updated in accorded with your topic.

I would recommend to add other constraints, like for example check if employee's date of birth is a valid date.

**Comment by Volod980** [comment]
Hello, thank you for your commets. Did I understand correctly that I should add some constraits and change a title according to my topic  and send you updated files? Is that all ?

**Comment by Volod980** [comment]
Hello, I changed the old files to the new ones with updated information. Could you please check them ?

**Review by albusel — APPROVED** [review]
HW approved, merge the branch.

**Pull request merged**
